services:
    mysql:
        image: mysql:9.0.1
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
    mysql-data:
