name: Laravel Deploy

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "*" ]

jobs:
  deploy:

    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # move entire folder to repo src
      - name: Move contents to repo root
        run: mv PAWX/* .

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Dependencies
        run: composer install

      - name: 'Copy .env'
        run: cp .env.sample .env

      - name: Migrate DB
        run: |
          php artisan migrate --force
        env:
          APP_ENV: production
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 6543
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          #MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt

      #- name: Deploy to Vercel
      #  run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} #--yes
      #  env:
      #    VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}
      #    VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
