name: Laravel Deploy

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "*" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Dependencies
        run: composer install

      - name: Migrate DB
        run: |
          php artisan migrate --force
        env:
          APP_ENV: production
          DB_CONNECTION: ${{ env.DB_CONNECTION }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_DATABASE: ${{ env.DB_DATABASE }}
          DB_USERNAME: ${{ env.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

#      - name: Deploy to Vercel
#        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
#        env:
#          VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}
#          VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
